In [54]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from ydata_profiling import ProfileReport
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC, SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from imblearn.over_sampling import SMOTE
from sklearn.naive_bayes import MultinomialNB

In [6]:
df = pd.read_csv("balanced_migraine_data.csv")

In [7]:
df=df.drop_duplicates()

In [8]:
df.head()

Age  Duration  Frequency  Location  Character  Intensity  Nausea  Vomit  \
0   30         1          5         1          1          2       1      0   
1   50         3          5         1          1          3       1      1   
2   53         2          1         1          1          2       1      1   
3   45         3          5         1          1          3       1      0   
4   53         1          1         1          1          2       1      0   

   Phonophobia  Photophobia  ...  Vertigo  Tinnitus  Hypoacusis  Diplopia  \
0            1            1  ...        0         0           0         0   
1            1            1  ...        1         0           0         0   
2            1            1  ...        0         0           0         0   
3            1            1  ...        1         0           0         0   
4            1            1  ...        0         0           0         0   

   Defect  Ataxia  Conscience  Paresthesia  DPF                        Type  
0       0       0           0            0    0  Typical aura with migraine  
1       0       0           0            0    0  Typical aura with migraine  
2       0       0           0            0    0  Typical aura with migraine  
3       0       0           0            0    0  Typical aura with migraine  
4       0       0           0            0    1  Typical aura with migraine  

[5 rows x 24 columns]

In [9]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [10]:
label_encoder = LabelEncoder()
df["Type"] = label_encoder.fit_transform(df["Type"])

In [11]:
df

Age  Duration  Frequency  Location  Character  Intensity  Nausea  Vomit  \
0      30         1          5         1          1          2       1      0   
1      50         3          5         1          1          3       1      1   
2      53         2          1         1          1          2       1      1   
3      45         3          5         1          1          3       1      0   
4      53         1          1         1          1          2       1      0   
...   ...       ...        ...       ...        ...        ...     ...    ...   
1663   46         1          4         0          0          0       1      0   
1671   21         3          2         0          0          0       1      0   
1673   31         1          2         0          0          0       1      0   
1675   25         1          4         0          0          0       1      0   
1680   24         2          1         0          0          0       1      0   

      Phonophobia  Photophobia  ...  Vertigo  Tinnitus  Hypoacusis  Diplopia  \
0               1            1  ...        0         0           0         0   
1               1            1  ...        1         0           0         0   
2               1            1  ...        0         0           0         0   
3               1            1  ...        1         0           0         0   
4               1            1  ...        0         0           0         0   
...           ...          ...  ...      ...       ...         ...       ...   
1663            1            1  ...        0         0           0         0   
1671            1            1  ...        0         0           0         0   
1673            1            1  ...        0         0           0         0   
1675            1            1  ...        0         0           0         0   
1680            1            1  ...        0         0           0         0   

      Defect  Ataxia  Conscience  Paresthesia  DPF  Type  
0          0       0           0            0    0     5  
1          0       0           0            0    0     5  
2          0       0           0            0    0     5  
3          0       0           0            0    0     5  
4          0       0           0            0    1     5  
...      ...     ...         ...          ...  ...   ...  
1663       0       0           0            0    0     6  
1671       0       0           0            0    1     6  
1673       0       0           0            0    0     6  
1675       0       0           0            0    1     6  
1680       0       0           0            0    1     6  

[953 rows x 24 columns]

In [12]:
df.shape

(953, 24)

In [13]:
df.duplicated().sum()

0

In [14]:
print(X)

      Age  Duration  Frequency  Location  Character  Intensity  Nausea  Vomit  \
0      30         1          5         1          1          2       1      0   
1      50         3          5         1          1          3       1      1   
2      53         2          1         1          1          2       1      1   
3      45         3          5         1          1          3       1      0   
4      53         1          1         1          1          2       1      0   
...   ...       ...        ...       ...        ...        ...     ...    ...   
1663   46         1          4         0          0          0       1      0   
1671   21         3          2         0          0          0       1      0   
1673   31         1          2         0          0          0       1      0   
1675   25         1          4         0          0          0       1      0   
1680   24         2          1         0          0          0       1      0   

      Phonophobia  Photopho

In [15]:
# Feature Engineering
from sklearn.feature_selection import SelectKBest, chi2, mutual_info_classif, f_classif

selector = SelectKBest(mutual_info_classif, k="all")
X = selector.fit_transform(X,y)
X

array([[30,  1,  5, ...,  0,  0,  0],
       [50,  3,  5, ...,  0,  0,  0],
       [53,  2,  1, ...,  0,  0,  0],
       ...,
       [31,  1,  2, ...,  0,  0,  0],
       [25,  1,  4, ...,  0,  0,  1],
       [24,  2,  1, ...,  0,  0,  1]], dtype=int64)

In [16]:
X.shape

(953, 23)

In [17]:
# Feature Scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)
X

array([[-0.0599369 , -0.76909729,  1.82033159, ..., -0.10806147,
        -0.06492275, -0.80902033],
       [ 1.65280279,  2.08840648,  1.82033159, ..., -0.10806147,
        -0.06492275, -0.80902033],
       [ 1.90971374,  0.6596546 , -0.73550783, ..., -0.10806147,
        -0.06492275, -0.80902033],
       ...,
       [ 0.02570008, -0.76909729, -0.09654797, ..., -0.10806147,
        -0.06492275, -0.80902033],
       [-0.48812183, -0.76909729,  1.18137173, ..., -0.10806147,
        -0.06492275,  1.23606289],
       [-0.57375881,  0.6596546 , -0.73550783, ..., -0.10806147,
        -0.06492275,  1.23606289]])

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [58]:
classifiers = {
    "Logistic Regression" : LogisticRegression(C=10, penalty="l1", solver="liblinear"),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(bootstrap=False, max_depth=20, min_samples_leaf=1, min_samples_split=5, n_estimators=200),
    "Support Vector Machine": SVC(kernel="poly", C=100, coef0=0, degree=3, gamma="scale", probability=True),
    "K Nearest Neighbors": KNeighborsClassifier(n_neighbors=1, weights="uniform", metric="euclidean")
}

In [59]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report, accuracy_score, recall_score, precision_score, f1_score

results = {}
for name, clf in classifiers.items():
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for {name}: \n", cm)
    accuracy = accuracy_score(y_test, y_pred)
    results[name]=accuracy
    print(f"{name} Accuracy: {accuracy*100:.2f}%")
    print(f"{name} Precision: {precision_score(y_test, y_pred, average="macro")*100:.2f}%")
    print(f"{name} Recall: {recall_score(y_test, y_pred, average="macro")*100:.2f}%")
    print(f"{name} F1_score: {f1_score(y_test, y_pred, average="macro")*100:.2f}%")
    print(classification_report(y_test, y_pred))
    print("-"*30)
            

Confusion Matrix for Logistic Regression: 
 [[19  0  3  0  1  2  0]
 [ 1 14  0  0  0  1  0]
 [ 0  0 34  0  0  0  0]
 [ 0  0  0 25  0  1  0]
 [ 0  0  0  0 13  3  0]
 [ 2  1  0  0  3 44  0]
 [ 0  0  0  0  0  0 24]]
Logistic Regression Accuracy: 90.58%
Logistic Regression Precision: 90.62%
Logistic Regression Recall: 89.84%
Logistic Regression F1_score: 90.13%
                               precision    recall  f1-score   support

            Basilar-type aura       0.86      0.76      0.81        25
 Familial hemiplegic migraine       0.93      0.88      0.90        16
        Migraine without aura       0.92      1.00      0.96        34
                        Other       1.00      0.96      0.98        26
 Sporadic hemiplegic migraine       0.76      0.81      0.79        16
   Typical aura with migraine       0.86      0.88      0.87        50
Typical aura without migraine       1.00      1.00      1.00        24

                     accuracy                           0.91       191

In [63]:
print("____________________TRIGGER IDENTIFICATION___________________________")

____________________TRIGGER IDENTIFICATION___________________________


In [ ]:
df.columns

Index(['Age', 'Duration', 'Frequency', 'Location', 'Character', 'Intensity',
       'Nausea', 'Vomit', 'Phonophobia', 'Photophobia', 'Visual', 'Sensory',
       'Dysphasia', 'Dysarthria', 'Vertigo', 'Tinnitus', 'Hypoacusis',
       'Diplopia', 'Defect', 'Ataxia', 'Conscience', 'Paresthesia', 'DPF',
       'Type'],
      dtype='object')

In [ ]:
X_test.shape

(191, 23)

In [ ]:
log = LogisticRegression()
log.fit(X_train, y_train)
y_pred = log.predict(X_test)
for i in range(7):
    print(f"Class {i}")
    coefficients = log.coef_[i]
    feature_importance = pd.DataFrame({'feature': df.columns[:-1], 'coefficient': coefficients})
    feature_importance['abs_coefficient'] = feature_importance['coefficient'].abs()
    feature_importance.sort_values(by='abs_coefficient', ascending=False, inplace=True)
    print(feature_importance)


Class 0
        feature  coefficient  abs_coefficient
14      Vertigo     1.369349         1.369349
2     Frequency    -1.173865         1.173865
6        Nausea     0.714904         0.714904
5     Intensity     0.687118         0.687118
15     Tinnitus     0.575053         0.575053
0           Age     0.567616         0.567616
16   Hypoacusis     0.527893         0.527893
10       Visual     0.495228         0.495228
12    Dysphasia    -0.480753         0.480753
8   Phonophobia     0.391201         0.391201
20   Conscience     0.363724         0.363724
1      Duration     0.305506         0.305506
7         Vomit    -0.286744         0.286744
9   Photophobia     0.285669         0.285669
18       Defect     0.222766         0.222766
21  Paresthesia     0.150077         0.150077
17     Diplopia     0.147091         0.147091
4     Character    -0.104699         0.104699
11      Sensory     0.096196         0.096196
3      Location    -0.091771         0.091771
22          DPF     0.0607

In [ ]:
y_train.value_counts()                                                      

Type
Typical aura with migraine       191
Migraine without aura            121
Other                            115
Basilar-type aura                 97
Typical aura without migraine     94
Familial hemiplegic migraine      81
Sporadic hemiplegic migraine      63
Name: count, dtype: int64